### ISSUE TITLE
Adding a proper documentation

### ISSUE THREAD

**Issue by HomerusJa** [pmateusz/meatie#114]
## Background

Currently, the documentation consists of a [README](https://github.com/HomerusJa/meatie/blob/master/README.md), a [cookbook markdown file](https://github.com/HomerusJa/meatie/blob/master/docs/cookbook.md), and examples under [tests/examples](https://github.com/HomerusJa/meatie/tree/master/tests/examples). While these provide good information, a more structured and comprehensive documentation would make the library more accessible to users and contributors. It would also give it a more professional look.

## MkDocs vs Sphinx

Both MkDocs and Sphinx are well-known solutions for documentation in the Python space. They each have their own pros and cons, so here is a quick comparison:

### MkDocs

Language: Markdown
Deployment: Preferably GitHub pages

You should use MkDocs, if ...
- your documentation's focus is primarily on user guides and tutorials. (I imagine the documentation for this repo is)
- you prefer the simplicity of Markdown. (I definitely do)
- you don’t mind manually managing API documentation or using third-party tools like mkdocstrings for code reference generation. (I believe as said above that the documentation for meatie would be most useful in the form of mostly guides)

### Sphinx

Language: reStructuredText, although Markdown can be integrated
Deployment: readthedocs.org

You should use Sphinx, if ...
- you want automated API reference generation from your code. (I don't really think it would be really useful in this project, as it is a meta-programming language and I think you can provide way more value with guides and examples, just my guess, still)
- you need extensive cross-referencing or version-specific documentation. (I don't really think so, right?)
- you plan to link to source code or use advanced customization features. (This could be, but I don't have a whole lot of experience in that realm so I can't really tell how big of an upside this would be)

As you might just have seen, I am really in favor of MkDocs, still, I figured I should leave that choice up to you. Following an issue which talks about using MkDocs and the specific steps needed to get there. I wrote that issue before I wrote this one.

<details>
<summary>Issue focused on MkDocs</summary>

## Backgound

This is as above

## Proposed Solution

Set up MkDocs with Material theme to create a full documentation site hosted on GitHub Pages.

### Implementation

An implementation would have multiple parts:

1. Create the basic structure using the following code:
   ```shell
   pip install mkdocs-material
   mkdocs new .
   ```
2. Setup the mkdocs.yaml
3. Setup a Github action workflow to automatically deploy the docs to Github pages. It would look something like this:
   ```yaml
   name: documentation
   on:
     push:
       branches:
         - master
   permissions:
     contents: write
   jobs:
     deploy:
       runs-on: ubuntu-latest
       steps:
         - uses: actions/checkout@v4
         - name: Configure Git Credentials
           run: |
             git config user.name github-actions[bot]
             git config user.email 41898282+github-actions[bot]@users.noreply.github.com
         - uses: actions/setup-python@v4
           with:
             python-version: 3.x
         - run: pip install mkdocs-material
         - run: mkdocs gh-deploy --force
   ```
4. Enable Github Pages
   - Go to repository Settings > Pages
   - Set
5. Add some links to the Readme and the repository links

The docs are now available under https://pmateusz.github.io/meatie/, which looks a bit ugly but I suppose you don't want to create an own organization for meatie yet.

## References
- [MkDocs Material Documentation](https://squidfunk.github.io/mkdocs-material/)
- [GitHub Pages Documentation](https://docs.github.com/en/pages)

</details>
